// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TypedSicm")>]
[<assembly: AssemblyProductAttribute("TypedSicm")>]
[<assembly: AssemblyDescriptionAttribute("Typed Sicm")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TypedSicm"
    let [<Literal>] AssemblyProduct = "TypedSicm"
    let [<Literal>] AssemblyDescription = "Typed Sicm"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
